### ISSUE TITLE
2 steps files generate one .pickled file

### ISSUE THREAD

**Issue by FlorianFlouquet** [PiotrFLEURY/pickled_cucumber#18]
**Describe the bug**
Having multiple steps files only product one .pickled file

**To Reproduce**
1. Create more than once steps files 
2. use "dart run build_runner build --delete-conflicting-outputs" command
3. only one .pickled file has been generated

**Expected behavior**
To have a .pickled file for each steps file.

**Comment by PiotrFLEURY** [comment]
Creating multiple step definition files will run the generator one time for each.

The root cause of the issue is that the generator tries to parse all the feature files in every generation instance.
