### ISSUE TITLE
Give more details on what cause the failure of the .pickled file creation

### ISSUE THREAD

**Issue by FlorianFlouquet** [PiotrFLEURY/pickled_cucumber#20]
**Is your feature request related to a problem? Please describe.**
When we use the command "dart run build_runner build --delete-conflicting-outputs" and it fails, the console shows an "bad element". It would be great if we have more details on which element cause the error.

**Describe the solution you'd like**
When a fail occured because a sentence in the .feature file isn't implemented, show a specific error message or return which line is the source of the failure.

**Comment by PiotrFLEURY** [comment]
Already noticed this. 
Thanks for opening this issue. 
It will be fixed in the next release
