### ISSUE TITLE
Test generation fails when adding multiple jira ticket number in the same feature file

### ISSUE THREAD

**Issue by FlorianFlouquet** [PiotrFLEURY/pickled_cucumber#23]
Describe the bug
When we have multiple scenarios in the same feature file, each of them link to a JIRA ticket number, we can't generate tests.

To Reproduce

Have a feature file like the below:
![image](https://github.com/PiotrFLEURY/pickled_cucumber/assets/64949896/7265e13a-8a9c-4c8b-a8bb-8e8c42dfac64)

When using the "dart run build_runner build --delete-conflicting-outputs" command in the console, you should get this exception:
![image](https://github.com/PiotrFLEURY/pickled_cucumber/assets/64949896/64d7b634-7770-4dbe-8d41-5672d824dead)

**Comment by PiotrFLEURY** [comment]
@FlorianFlouquet unfortunately I was not able to reproduce the issue.

Can you look at this pull request and see if I missed something ?

[https://github.com/PiotrFLEURY/pickled_cucumber/pull/24](https://github.com/PiotrFLEURY/pickled_cucumber/pull/24)

As you can see, every test passed and the CI sounds good.

**Comment by FlorianFlouquet** [comment]
My explanation of the issue was wrong, sorry. I updated the issue with a more detailed example to reproduce the issue.

**Comment by PiotrFLEURY** [comment]
@FlorianFlouquet the issue was successfully reproduced and fixed

Please update to the new [1.0.4 version on pub.dev](https://pub.dev/packages/pickled_cucumber)

Thank you for you issue report and for using pickled_cucumber !
